import "dotenv/config";

export const client = {
  businessName: "The Gloss Spot Auto Detailing",
  ownerName: "Dominic Pierson",
  phone: "217-600-2108",
  email: "theglossspotil@gmail.com",
  address: "Champaign County, IL",
  city: "Champaign",
  state: "IL",
  zip: "61822",

  niche: "Car Detailing",
  nicheKeyword: "car detailing",
  nicheSlug: "car-detailing",

  cities: ["Champaign", "Urbana", "Savoy", "Mahomet", "Rantoul", "St. Joseph", "Tolono", "Danville", "Decatur", "Bloomington", "Normal", "Mattoon", "Monticello", "Kankakee", "Springfield", "Philo", "Sidney", "Ogden", "Fisher", "Thomasboro", "Peoria", "Charleston", "Effingham"],

  services: [
    "mobile detailing",
    "interior detailing",
    "exterior detailing",
    "full service detailing",
    "ceramic coating",
    "paint correction",
    "headlight restoration",
    "engine detailing",
    "paint protection film",
    "window tinting",
    "car wraps",
    "motorcycle detailing",
    "fleet detailing",
    "dealership detailing",
    "rental car detailing",
    "body shop detailing",
  ],

  primaryColor: "#02888a",
  accentColor: "#5cd9db",
  secondaryColor: "",
  textColor: "#222222",
  footerColor: "#0a0a0a",
  logo: "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_200/Gloss_Spot_500_x_500_px_1_eviirr",
  logoWide: "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_400/Gloss_Spot_4_h1brcd",
  favicon: "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_64/Gloss_Spot_500_x_500_px_1_eviirr",

  // ── Photos ──────────────────────────────────────────────────────────────
  // Real Gloss Spot photos hosted on Cloudinary. f_auto/q_auto in the URL
  // tells Cloudinary to auto-pick WebP/AVIF + optimal quality per browser.
  // To swap any of these: paste a new Cloudinary URL (full URL, not just ID).
  // To go back to placeholders: empty out the value.
  photos: {
    hero: [
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_1800/IMG_5948_totw8k",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_1800/IMG_6007_huulif",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_1800/IMG_6010_bgc6ll",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_1800/IMG_6011_xle1gg",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_1800/IMG_6240_n97i25",
    ],
    heroVideo: "https://res.cloudinary.com/djp1yfsj5/video/upload/09e0136d1e1a49dea649dcc5c012cde3_u6qrks_e3j2v4",
    gallery: [
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5310_xepias",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5403_sy036b",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5605_gw8kiq",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5876_d9uiq0",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5970_gc28l5",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_6231_zxhqub",
    ],
    value: "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_1100/IMG_5969_pmvndg",
    bigCta: "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_1800/IMG_6283_oxnzvf",
    owner: "",  // placeholder — paste Dom's photo URL when ready
    blog: [
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5605_gw8kiq",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5853_cxrrpb",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5644_zeces6",
      "https://res.cloudinary.com/djp1yfsj5/image/upload/f_auto,q_auto,w_900/IMG_5582_d2eijo",
    ],
  },

  headlineFont: "Bebas Neue",
  bodyFont: "Inter",
  headlineSize: "64px",

  heroHeadline: "",
  heroSubheadline: "",
  heroBackground: "",
  heroCTA1: "Book Now",
  heroCTA2: "Get Free Quote",

  trustPoints: [
    "Mobile — We Come To You",
    "60+ Five-Star Reviews",
    "Licensed & Insured",
    "Same-Day Available",
  ],

  stats: [
    { number: "60+", label: "5-Star Reviews" },
    { number: "5★", label: "Google Rating" },
    { number: "100%", label: "Mobile Service" },
    { number: "100%", label: "Satisfaction" },
  ],

  // Total reviews displayed in "X+ five-star reviews" copy + JSON-LD schema.
  // We have 59 review texts but the actual Google count is 90+.
  reviewCount: 90,

  reviews: [
    { name: "Shelbi Hynds", city: "Champaign", rating: 5, text: "SERVICE OF THE YEAR!!!!! I have taken my car to get detailed before but having them come to you and doing a 15/10 job! Couldn't have asked for anything better! Would highly recommend!" },
    { name: "Macy Ruple", city: "Champaign", rating: 5, text: "Dom was incredible!!! Our car belonged to friends before us, it's a 2008, so I never expected perfection. When I say this is the cleanest I've EVER seen this car… I'm FLOORED." },
    { name: "Sheila T", city: "Champaign", rating: 5, text: "The quality of the work was excellent. I lost a ring seven years ago — a family heirloom that belonged to my mother who passed 20 years ago. They found the ring under my seat. Worth every penny." },
    { name: "Cassandra Beer", city: "Champaign", rating: 5, text: "I have 4 kids and spend a great deal of time in my van. Despite vacuuming once a week, it looks horrid. Dom, however, cleans it like brand new. He takes a lot of pride in his work and it shows." },
    { name: "Samantha Gannon", city: "Champaign", rating: 5, text: "If I could rate 1 million stars, I would! Made me feel like I was driving a brand new car home! They came straight to my job so I didn't have to schedule around anything. WILL ABSOLUTELY BOOK AGAIN!" },
    { name: "Kevin Clark", city: "Champaign", rating: 5, text: "I had my 2024 black Suburban detailed by Gloss Spot. They did an awesome job. It looks better than when I brought it home. Very detail oriented, professional service." },
    { name: "Kenny Nguyen", city: "Champaign", rating: 5, text: "From knocking on my door to bringing my car back to life, Gloss Spot has truly surprised me with how great their work is. Dominic takes a lot of pride in his work — the dog hair removal and leather conditioning made a huge difference." },
    { name: "TT Y", city: "Champaign", rating: 5, text: "Dom did such an amazing job on my car! The outside is sparkling clean and shiny, and the inside looks super fresh and spotless. It honestly feels like I'm driving a brand-new car again." },
    { name: "Blake Goodman", city: "Champaign", rating: 5, text: "I work a labor job plus I have a very messy dog so it gets dirty very quickly and he got it all out! It looks amazing and smells great just like when I first bought it." },
    { name: "Raj Smith", city: "Champaign", rating: 5, text: "Dom is the man!!! He did an amazing job with my Yukon. Very detail oriented and will make your car look amazing. Will come back again!" },
    { name: "Paige R", city: "Champaign", rating: 5, text: "We had the best experience when we brought our car here to have the interior detailed. Dom was extremely professional, friendly, and our car came out perfect." },
    { name: "Mark Howard", city: "Champaign", rating: 5, text: "The Gloss Spot Auto Detailing did a fantastic job on my F150. I'd recommend them highly!" },
    { name: "Reese Donsbach", city: "Champaign", rating: 5, text: "Just got back from vacation in Florida and my car was an absolute disaster after 12 hours of driving each way. I thought it would never look the same. They made it look new again." },
    { name: "Eric Fagerlin", city: "Champaign", rating: 5, text: "They came to where my car was and had all their equipment with them. Very professional, accommodating, and thorough. When it was done I was blown away by how nice my car looked and smelled!" },
    { name: "Robert Wengert", city: "Champaign", rating: 5, text: "I own a twelve year old Toyota Avalon. The headlight covers had become blurry and yellowish. Gloss Spot cleared them right up. Outstanding service." },
    { name: "Kishan Patel", city: "Champaign", rating: 5, text: "They went above and beyond to make sure every corner of my car was spotless inside and out. My car hasn't looked this good since the day I bought it. Definitely worth every penny!" },
    { name: "Elizabeth Churchya", city: "Champaign", rating: 5, text: "Impeccable service! Arrived promptly as scheduled and was extremely thorough with both interior and exterior detailing. Car was left extremely clean with a fresh but not overpowering scent." },
    { name: "Katie Pierson", city: "Champaign", rating: 5, text: "The Gloss Spot did such an amazing job on my detail making my 2016 Jeep look brand new. The extra convenience of them coming to my house was amazing!" },
    { name: "Artem Pichshuk", city: "Champaign", rating: 5, text: "Got my car done by Dominic. Really polite young man. Really happy with my squeaky clean car!" },
    { name: "Isis Rose", city: "Urbana", rating: 5, text: "The technician met me at a convenient location and did a great job detailing my car's interior! I don't remember the last time my car was this clean! Signed, a mom of 2." },
    { name: "Chad Detamore", city: "Champaign", rating: 5, text: "Great to see such hard working young men. They do an awesome job and will have your car looking as good as new. Best part is they come to you — very convenient!" },
    { name: "Jordan Gebil Neal", city: "Champaign", rating: 5, text: "I've used this service twice now for interior cleaning. Always amazed at how good my car looks afterward. So convenient that he comes right to your house, and he's super friendly and professional." },
    { name: "Stephanie Fonseca", city: "Champaign", rating: 5, text: "Customer service was professional, and he did an excellent job cleaning both the inside and outside of my car. Definitely recommend if you're looking for quality work and reliable service." },
    { name: "Derek Rankin", city: "Mahomet", rating: 5, text: "Dom did an excellent job detailing our vehicle! The full service detail was thorough and convenient, as he came to our home in Mahomet." },
    { name: "John Lawyer", city: "Champaign", rating: 5, text: "Outstanding job. Made my wife's car look like new, and washed my truck that had road tar and diesel stains. His cleaner did a better job and faster than the solvent I normally use." },
    { name: "Kerry Navarro", city: "Champaign", rating: 5, text: "I finally got it together and had Gloss Spot come over to detail my car top to bottom and I could not be happier! Excellent customer service, professional from start to finish." },
    { name: "Genesis Gebil", city: "Champaign", rating: 5, text: "Dom has been taking care of mine and my mom's car for a while now, and every time, the results have been amazing. We keep coming back because of the quality and care he puts into every detail." },
    { name: "Alien", city: "Champaign", rating: 5, text: "10/10, perfect experience. They went above and beyond in all areas and it really is the best customer experience I've ever had at a car detailing." },
    { name: "Jim Keiken", city: "Champaign", rating: 5, text: "Dom did terrific work. My truck looks showroom new, everything spotless inside and out. Professional operation from scheduling to final product." },
    { name: "Angel Ybarra", city: "Urbana", rating: 5, text: "Amazing work! 10 out of 10 full detail service inside and out. Came to my residence outskirts of Urbana. Will be booking again." },
    { name: "Katelynn Nguyen", city: "Champaign", rating: 5, text: "The detailing was PERFECT. My 13yr old SUV looks brand new, from the exterior to the leather seats. I couldn't be happier with the results!" },
    { name: "Jeffrey Davis", city: "Champaign", rating: 5, text: "5 stars ain't enough. Showed up the day after I called on the weekend to clean out my A-to-B car and I wasn't expecting it to look this good in its life. Great customer service and a well-run business." },
    { name: "Karen West", city: "Champaign", rating: 5, text: "They did a great job. Loved that they came to my house. They even brought their own water supply. Would highly recommend." },
    { name: "Lina Abbadi", city: "Champaign", rating: 5, text: "Dom was super chill and professional and obviously takes pride in his work. My car looks and FEELS so clean — I could have never done a job that good myself. My car was filthy when I first bought it used." },
    { name: "Saad Aqeel", city: "Champaign", rating: 5, text: "Great experience overall! He came to my home for car detailing and did an amazing job. Very professional, on time, and paid attention to every detail." },
    { name: "Victoria Todd", city: "Champaign", rating: 5, text: "Saved me hours of cleaning and did 20 times better than I ever could on my own. Very convenient coming to wherever you are. Got it done while at work so I drove off after my shift with it spotless and smelling great." },
    { name: "Kim Pillischafske", city: "Champaign", rating: 5, text: "The young man who detailed my car inside and out did an amazing job! I only wish I wasn't driving it to NC, because it will be covered in yellow pollen!" },
    { name: "Ravie Ezeoke", city: "Champaign", rating: 5, text: "Did a wonderful job cleaning our car! He was very flexible and accommodating to us." },
    { name: "Nathan", city: "Champaign", rating: 5, text: "Dom is a cool guy. Super helpful and did a great job on my vehicle." },
    { name: "Olivia Schrader", city: "Champaign", rating: 5, text: "I am really glad I decided to get my car detailed by The Gloss Spot! They did an amazing job cleaning up my car." },
    { name: "Mason McCaffrey", city: "Champaign", rating: 5, text: "Amazing work from these guys. Made my car look literally brand new!" },
    { name: "Amere Brown", city: "Champaign", rating: 5, text: "Very great detail, these guys exceeded my expectations and I will definitely keep letting them detail my car." },
    { name: "Ella Tangen", city: "Champaign", rating: 5, text: "My car looks brand new. They did such a great job. I would totally recommend and use them again!" },
    { name: "Doug Bartlett Jr", city: "Champaign", rating: 5, text: "Very nice job! Great communication and easy to work with. Definitely recommend." },
    { name: "Chris Ebisuya", city: "Champaign", rating: 5, text: "These guys do a great job! They come to you, my car gets cleaned while I'm at work." },
    { name: "Landon Natschke", city: "Mahomet", rating: 5, text: "100% recommend. They did my interior and exterior in Mahomet." },
    { name: "Nico Micele", city: "Champaign", rating: 5, text: "Full service detailing, straight to my home in Champaign. They did amazing!" },
    { name: "Dayo Hunley", city: "Champaign", rating: 5, text: "Had the full detail done and would definitely recommend to others." },
    { name: "Guan Zhiyuan", city: "Champaign", rating: 5, text: "They did a great job on cleaning my car and it looked like a brand new one. Nice people with great service." },
    { name: "Felix Alejandro", city: "Champaign", rating: 5, text: "Excellent job. My car looks like new." },
    { name: "Ron Thiele", city: "Champaign", rating: 5, text: "Very satisfied with the work done detailing the car's interior." },
    { name: "Bross", city: "Champaign", rating: 5, text: "Great work in good time. Can't go wrong with the Gloss Spot." },
    { name: "Kylia Pierson", city: "Champaign", rating: 5, text: "Very efficient and know what they are doing. Money well spent!" },
    { name: "Gary Pierson", city: "Champaign", rating: 5, text: "Fast! Convenient! And friendly service." },
    { name: "Krystal Jackson", city: "Champaign", rating: 5, text: "These young men did a wonderful job on my car!" },
    { name: "Mary Kelly", city: "Champaign", rating: 5, text: "Service was really good!" },
    { name: "Jackson Biddle", city: "Champaign", rating: 5, text: "Does a great job." },
    { name: "Ace", city: "Champaign", rating: 5, text: "10/10 would recommend to anyone." },
    { name: "KillaKaw", city: "Champaign", rating: 5, text: "Did a good job at a reasonable price. I recommend!" },
  ],

  hours: "Mon-Sat: 8am-8pm, Sun: 1pm-8pm",
  emergencyService: false,

  facebook: "https://www.facebook.com/theglossspot",
  instagram: "https://www.instagram.com/theglossspotil",
  google: "https://share.google/Wr0NTsR0CmFTlYRtk",
  yelp: "https://www.yelp.com/biz/the-gloss-spot-auto-detailing-champaign-3",

  blogPostsPerDay: 3,
  blogAuthorName: "The Gloss Spot Team",
  blogAuthorTitle: "Mobile Detailing Specialists",
  blogAuthorBio: "The Gloss Spot is a brother-run mobile detailing business proudly serving Champaign-Urbana and surrounding areas. We bring showroom-quality results directly to your driveway.",

  footerTagline: "Premium mobile detailing across Champaign-Urbana. We come to you.",
  showSocial: true,
  showCities: true,
  showServices: true,

  googleAnalyticsId: "",
  facebookPixelId: "",

  includeAboutPage: false,
  includeContactPage: false,
  includeServicePages: false,
  includeCityPages: true,
  includeBlogPage: true,

  domain: "https://theglossspotil.com",

  anthropicApiKey: process.env.ANTHROPIC_API_KEY,
  ghlApiKey:       process.env.GHL_API_KEY       || "",
  ghlLocationId:   process.env.GHL_LOCATION_ID   || "",
  indexNowKey:     process.env.INDEXNOW_KEY       || "",
};